# Generated by Django 3.1.5 on 2021-06-17 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('work_id', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2021, 6, 17, 12, 58, 53, 804936))),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('deadline', models.DateTimeField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
